### ISSUE TITLE
Axies class column is not translated

### ISSUE THREAD

**Issue by e1Ru1o** [Axie-Management-Team/axie.management.languages#18]
The tables displaying the Axies are not using the translations in the class column.

**Comment by blanxii** [comment]
@e1Ru1o Which one do you refer? can you attack screenshot please?

**Comment by blanxii** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/18527021/138064974-738fa66b-9df6-4946-8b6e-fc177efe2ac7.png)
